name: Manual AI Assistant
on:
  issues:
    types: [labeled]

jobs:
  remind:
    runs-on: ubuntu-latest
    steps:
      - name: Notify about manual AI
        run: |
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"body": "Владелец репозитория: запросите анализ у @allservis в DeepSeek Chat."}' \
            "${{ github.event.issue.comments_url }}"
